default_stages: [commit]
repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: system
        entry: bash -c "cd app && pnpm pretty"
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: system
        entry: bash -c "cd app && pnpm lint"
